/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as PortofolioRouteImport } from './routes/portofolio'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as KontakKamiRouteImport } from './routes/kontak-kami'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KarirIndexRouteImport } from './routes/karir.index'
import { Route as KarirJobIdRouteImport } from './routes/karir.$jobId'

const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofolioRoute = PortofolioRouteImport.update({
  id: '/portofolio',
  path: '/portofolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakKamiRoute = KontakKamiRouteImport.update({
  id: '/kontak-kami',
  path: '/kontak-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KarirIndexRoute = KarirIndexRouteImport.update({
  id: '/karir/',
  path: '/karir/',
  getParentRoute: () => rootRouteImport,
} as any)
const KarirJobIdRoute = KarirJobIdRouteImport.update({
  id: '/karir/$jobId',
  path: '/karir/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/kontak-kami': typeof KontakKamiRoute
  '/layanan': typeof LayananRoute
  '/portofolio': typeof PortofolioRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/karir/$jobId': typeof KarirJobIdRoute
  '/karir/': typeof KarirIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/kontak-kami': typeof KontakKamiRoute
  '/layanan': typeof LayananRoute
  '/portofolio': typeof PortofolioRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/karir/$jobId': typeof KarirJobIdRoute
  '/karir': typeof KarirIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/kontak-kami': typeof KontakKamiRoute
  '/layanan': typeof LayananRoute
  '/portofolio': typeof PortofolioRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/karir/$jobId': typeof KarirJobIdRoute
  '/karir/': typeof KarirIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/kontak-kami'
    | '/layanan'
    | '/portofolio'
    | '/tentang-kami'
    | '/karir/$jobId'
    | '/karir/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/kontak-kami'
    | '/layanan'
    | '/portofolio'
    | '/tentang-kami'
    | '/karir/$jobId'
    | '/karir'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/kontak-kami'
    | '/layanan'
    | '/portofolio'
    | '/tentang-kami'
    | '/karir/$jobId'
    | '/karir/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  KontakKamiRoute: typeof KontakKamiRoute
  LayananRoute: typeof LayananRoute
  PortofolioRoute: typeof PortofolioRoute
  TentangKamiRoute: typeof TentangKamiRoute
  KarirJobIdRoute: typeof KarirJobIdRoute
  KarirIndexRoute: typeof KarirIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofolio': {
      id: '/portofolio'
      path: '/portofolio'
      fullPath: '/portofolio'
      preLoaderRoute: typeof PortofolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak-kami': {
      id: '/kontak-kami'
      path: '/kontak-kami'
      fullPath: '/kontak-kami'
      preLoaderRoute: typeof KontakKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karir/': {
      id: '/karir/'
      path: '/karir'
      fullPath: '/karir/'
      preLoaderRoute: typeof KarirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karir/$jobId': {
      id: '/karir/$jobId'
      path: '/karir/$jobId'
      fullPath: '/karir/$jobId'
      preLoaderRoute: typeof KarirJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  KontakKamiRoute: KontakKamiRoute,
  LayananRoute: LayananRoute,
  PortofolioRoute: PortofolioRoute,
  TentangKamiRoute: TentangKamiRoute,
  KarirJobIdRoute: KarirJobIdRoute,
  KarirIndexRoute: KarirIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
